#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/table.ls -> dist/index.js ..."
./node_modules/.bin/lsc -cpb --no-header src/table.ls > dist/index.js
echo "build src/code.ls -> dist/index.js ..."
./node_modules/.bin/lsc -cpb --no-header src/code.ls >> dist/index.js
echo "minifying index.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js
echo "done."
